stages:
  - deploy

staging:
  stage: deploy
  script:
    - cd /var/www/nginx/artis-dapps-keys-generation
    - git pull
    - . ~/.nvm/nvm.sh
    - npm ci
    - rm -r build
    - CI=false npm run build